id = "wm-lang"
name = "Workman language support"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "My cool extension"
repository = "https://github.com/your-name/my-zed-extension"

[grammars.workman]
repository = "file:///c:/GIT/zedExtension/tree-sitter-workman"
rev = "a2ab886aba637457fa87ebd4c51c69316c3c437a"

[language_servers.workman-lsp]
name = "Workman Language Server"
languages = ["Workman"]
